apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-apps
  namespace: ns-team1
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "k8s-prd-java.sathyalabs.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-java-demo
            port:
              number: 80

